import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import InpageNavigation from "./InpageNavigation";

const MatchDetails = () => {
  let { id } = useParams();
  // console.log(id);

  let fixedData = {
    matchInfo: {
      matchId: 114960,
      matchDescription: "1st Match",
      matchFormat: "T20",
      matchType: "league",
      complete: true,
      domestic: false,
      matchStartTimestamp: 1742652000000,
      matchCompleteTimestamp: 1742663855945,
      dayNight: false,
      year: 2025,
      state: "complete",
      team1: {
        id: 63,
        name: "Kolkata Knight Riders",
        playerDetails: [
          {
            id: 8520,
            name: "de Kock",
            fullName: "Quinton de Kock",
            nickName: "de Kock",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "KKR",
            faceImageId: 594326,
            isOverseas: true,
          },
          {
            id: 10917,
            name: "Venkatesh Iyer",
            fullName: "Venkatesh Iyer",
            nickName: "Venkatesh Iyer",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm medium",
            teamName: "KKR",
            faceImageId: 226278,
          },
          {
            id: 1447,
            name: "Ajinkya Rahane",
            fullName: "Ajinkya Rahane",
            nickName: "Rahane",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "KKR",
            faceImageId: 332892,
          },
          {
            id: 10896,
            name: "Rinku Singh",
            fullName: "Rinku Singh",
            nickName: "Rinku Singh",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "KKR",
            faceImageId: 279125,
          },
          {
            id: 22566,
            name: "Angkrish Raghuvanshi",
            fullName: "Angkrish Raghuvanshi",
            nickName: "Angkrish Raghuvanshi",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "KKR",
            faceImageId: 626309,
            inMatchChange: "MOUT",
          },
          {
            id: 2276,
            name: "Narine",
            fullName: "Sunil Narine",
            nickName: "Narine",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "KKR",
            faceImageId: 152654,
            isOverseas: true,
          },
          {
            id: 7736,
            name: "Russell",
            fullName: "Andre Russell",
            nickName: "Russell",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "KKR",
            faceImageId: 170821,
            isOverseas: true,
          },
          {
            id: 12337,
            name: "Ramandeep Singh ",
            fullName: "Ramandeep Singh ",
            nickName: "Ramandeep Singh ",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "KKR",
            faceImageId: 182026,
          },
          {
            id: 13143,
            name: "Spencer Johnson",
            fullName: "Spencer Johnson",
            nickName: "Spencer Johnson",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "KKR",
            faceImageId: 619884,
            isOverseas: true,
          },
          {
            id: 24729,
            name: "Harshit Rana",
            fullName: "Harshit Rana",
            nickName: "Harshit Rana",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "KKR",
            faceImageId: 616529,
          },
          {
            id: 12926,
            name: "Varun Chakaravarthy",
            fullName: "Varun Chakaravarthy",
            nickName: "Varun Chakaravarthy",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "KKR",
            faceImageId: 616528,
          },
          {
            id: 11427,
            name: "Nortje",
            fullName: "Anrich Nortje",
            nickName: "Nortje",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "KKR",
            faceImageId: 244754,
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 1836,
            name: "Manish Pandey",
            fullName: "Manish Pandey",
            nickName: "Manish Pandey",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "KKR",
            faceImageId: 171022,
            splSubstitute: true,
          },
          {
            id: 15861,
            name: "Vaibhav Arora",
            fullName: "Vaibhav Arora",
            nickName: "Vaibhav Arora",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "KKR",
            faceImageId: 182026,
            inMatchChange: "MIN",
            splSubstitute: true,
          },
          {
            id: 12344,
            name: "Anukul Roy",
            fullName: "Anukul Roy",
            nickName: "Anukul Roy",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "KKR",
            faceImageId: 593785,
            splSubstitute: true,
          },
          {
            id: 13972,
            name: "Luvnith Sisodia",
            fullName: "Luvnith Sisodia",
            nickName: "Luvnith Sisodia",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "KKR",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 13213,
            name: "Gurbaz",
            fullName: "Rahmanullah Gurbaz",
            nickName: "Gurbaz",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "KKR",
            faceImageId: 616556,
            isOverseas: true,
          },
          {
            id: 6692,
            name: "Moeen",
            fullName: "Moeen Ali",
            nickName: "Moeen Ali",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "KKR",
            faceImageId: 597794,
            isOverseas: true,
          },
          {
            id: 11445,
            name: "Rovman Powell",
            fullName: "Rovman Powell",
            nickName: "Powell",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "KKR",
            faceImageId: 244832,
            isOverseas: true,
          },
          {
            id: 12627,
            name: "Markande",
            fullName: "Mayank Markande",
            nickName: "Markande",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "KKR",
            faceImageId: 226510,
          },
          {
            id: 13494,
            name: "Chetan Sakariya",
            fullName: "Chetan Sakariya",
            nickName: "Sakariya",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "KKR",
            faceImageId: 169708,
          },
          {
            id: 3870,
            name: "Chandrakant Pandit",
            fullName: "Chandrakant Pandit",
            nickName: "Pandit",
            role: "Head coach",
            teamId: 63,
            teamName: "KKR",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 3873,
            name: "Bharat Arun",
            fullName: "Bharat Arun",
            nickName: "Arun",
            role: "Bowling coach",
            teamId: 63,
            teamName: "KKR",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 242,
            name: "Dwayne Bravo",
            fullName: "Dwayne Bravo",
            nickName: "Dwayne Bravo",
            role: "Mentor",
            teamId: 63,
            teamName: "KKR",
            faceImageId: 171033,
            isSupportStaff: true,
          },
          {
            id: 1451668,
            name: "Carl Crowe",
            fullName: "Carl Crowe",
            nickName: "Carl Crowe",
            role: "Spin Bowling Coach",
            teamId: 63,
            teamName: "KKR",
            faceImageId: 182026,
            isSupportStaff: true,
          },
        ],
        shortName: "KKR",
      },
      team2: {
        id: 59,
        name: "Royal Challengers Bengaluru",
        playerDetails: [
          {
            id: 1413,
            name: "Kohli",
            fullName: "Virat Kohli",
            nickName: "Kohli",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "RCB",
            faceImageId: 616517,
          },
          {
            id: 10479,
            name: "Phil Salt",
            fullName: "Philip Salt",
            nickName: "Phil Salt",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "RCB",
            faceImageId: 617408,
            isOverseas: true,
          },
          {
            id: 10636,
            name: "Rajat Patidar",
            fullName: "Rajat Patidar",
            nickName: "Rajat Patidar",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "RCB",
            faceImageId: 234983,
          },
          {
            id: 10045,
            name: "Livingstone",
            fullName: "Liam Livingstone",
            nickName: "Livingstone",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "RCB",
            faceImageId: 617405,
            isOverseas: true,
          },
          {
            id: 10214,
            name: "Jitesh Sharma",
            fullName: "Jitesh Sharma",
            nickName: "Jitesh Sharma",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "RCB",
            faceImageId: 226474,
          },
          {
            id: 13169,
            name: "Tim David",
            fullName: "Tim David",
            nickName: "Tim David",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "RCB",
            faceImageId: 594298,
            isOverseas: true,
          },
          {
            id: 11311,
            name: "Krunal Pandya",
            fullName: "Krunal Pandya",
            nickName: "Krunal Pandya",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "RCB",
            faceImageId: 171069,
          },
          {
            id: 14274,
            name: "Rasikh Salam",
            fullName: "Rasikh Dar Salam",
            nickName: "Rasikh Salam",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 182026,
          },
          {
            id: 36487,
            name: "Suyash Sharma",
            fullName: "Suyash Sharma",
            nickName: "Suyash Sharma",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "RCB",
            faceImageId: 182026,
            inMatchChange: "MOUT",
          },
          {
            id: 6258,
            name: "Hazlewood",
            fullName: "Josh Hazlewood",
            nickName: "Hazlewood",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 352459,
            isOverseas: true,
          },
          {
            id: 14172,
            name: "Yash Dayal",
            fullName: "Yash Dayal",
            nickName: "Yash Dayal",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "RCB",
            faceImageId: 182026,
          },
          {
            id: 13088,
            name: "Padikkal",
            fullName: "Devdutt Padikkal",
            nickName: "Padikkal",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "RCB",
            faceImageId: 591960,
            inMatchChange: "MIN",
            splSubstitute: true,
          },
          {
            id: 1447073,
            name: "Abhinandan Singh",
            fullName: "Abhinandan Singh",
            nickName: "Abhinandan Singh",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 13962,
            name: "Manoj Bhandage",
            fullName: "Manoj Bhandage",
            nickName: "Bhandage",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 13646,
            name: "Romario Shepherd",
            fullName: "Romario Shepherd",
            nickName: "Shepherd",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 593798,
            splSubstitute: true,
            isOverseas: true,
          },
          {
            id: 10238,
            name: "Swapnil Singh",
            fullName: "Swapnil Singh",
            nickName: "Swapnil Singh",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Left arm orthodox",
            teamName: "RCB",
            faceImageId: 182026,
            splSubstitute: true,
          },
          {
            id: 1726,
            name: "Bhuvneshwar",
            fullName: "Bhuvneshwar Kumar",
            nickName: "Bhuvneshwar",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 244967,
          },
          {
            id: 9603,
            name: "Lungi Ngidi",
            fullName: "Lungi Ngidi",
            nickName: "Ngidi",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "RCB",
            faceImageId: 619872,
            isOverseas: true,
          },
          {
            id: 18509,
            name: "N Thushara",
            fullName: "Nuwan Thushara",
            nickName: "N Thushara",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "RCB",
            faceImageId: 226338,
            isOverseas: true,
          },
          {
            id: 19636,
            name: "Jacob Bethell",
            fullName: "Jacob Bethell",
            nickName: "Jacob Bethell",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "RCB",
            faceImageId: 599742,
            isOverseas: true,
          },
          {
            id: 36524,
            name: "Mohit Rathee",
            fullName: "Mohit Rathee",
            nickName: "Mohit Rathee",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "RCB",
            faceImageId: 182026,
          },
          {
            id: 52418,
            name: "Swastik Chikara",
            fullName: "Swastik Chikara",
            nickName: "Swastik Chikara",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 59,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "RCB",
            faceImageId: 182026,
          },
          {
            id: 8899,
            name: "Malolan Rangarajan",
            fullName: "Malolan Rangarajan",
            nickName: "Malolan Rangarajan",
            role: "Head of Scouting and Fielding Coach",
            teamId: 59,
            teamName: "RCB",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 3406,
            name: "Andy Flower",
            fullName: "Andy Flower",
            nickName: "Flower",
            role: "Head Coach",
            teamId: 59,
            teamName: "RCB",
            faceImageId: 153350,
            isSupportStaff: true,
          },
          {
            id: 42663,
            name: "Adam Griffith",
            fullName: "Adam Griffith",
            nickName: "Adam Griffith",
            role: "Bowling Coach",
            teamId: 59,
            teamName: "RCB",
            faceImageId: 182026,
            isSupportStaff: true,
          },
          {
            id: 145,
            name: "Dinesh Karthik",
            fullName: "Dinesh Karthik",
            nickName: "Karthik",
            role: "Batting coach and Mentor",
            teamId: 59,
            teamName: "RCB",
            faceImageId: 244969,
            isSupportStaff: true,
          },
        ],
        shortName: "RCB",
      },
      series: {
        id: 9237,
        name: "Indian Premier League 2025",
        seriesType: "IPL",
        startDate: 1742515200000,
        endDate: 1748217600000,
        seriesFolder: "",
        odiSeriesResult: "",
        t20SeriesResult: "''",
        testSeriesResult: "",
        tournament: true,
      },
      umpire1: {
        id: 10601,
        name: "Abhijeet Bengeri",
        country: "IND",
      },
      umpire2: {
        id: 13663,
        name: "Vinod Seshan",
        country: "IND",
      },
      umpire3: {
        id: 8905,
        name: "Jayaraman Madanagopal",
        country: "IND",
      },
      referee: {
        id: 9225,
        name: "Prakash Bhatt",
        country: "IND",
      },
      tossResults: {
        tossWinnerId: 59,
        tossWinnerName: "Royal Challengers Bengaluru",
        decision: "Bowling",
      },
      result: {
        resultType: "win",
        winningTeam: "Royal Challengers Bengaluru",
        winningteamId: 59,
        winningMargin: 7,
        winByRuns: false,
        winByInnings: false,
      },
      venue: {
        id: 31,
        name: "Eden Gardens",
        city: "Kolkata",
        country: "India",
        timezone: "+05:30",
        latitude: "22.564527",
        longitude: "88.343247",
      },
      status: "Royal Challengers Bengaluru opt to bowl",
      playersOfTheMatch: [
        {
          id: 11311,
          name: "Krunal Pandya",
          fullName: "Krunal Pandya",
          nickName: "Krunal Pandya",
          captain: false,
          keeper: false,
          substitute: false,
          teamName: "Mumbai Indians",
          faceImageId: 171069,
        },
      ],
      playersOfTheSeries: [],
      revisedTarget: {
        reason: "",
      },
      matchTeamInfo: [
        {
          battingTeamId: 63,
          battingTeamShortName: "KKR",
          bowlingTeamId: 59,
          bowlingTeamShortName: "RCB",
        },
        {
          battingTeamId: 59,
          battingTeamShortName: "RCB",
          bowlingTeamId: 63,
          bowlingTeamShortName: "KKR",
        },
      ],
      isMatchNotCovered: false,
      HYSEnabled: 1,
      livestreamEnabled: false,
      isFantasyEnabled: true,
      livestreamEnabledGeo: [
        "MA",
        "KW",
        "EG",
        "TN",
        "JO",
        "MR",
        "US",
        "BH",
        "SD",
        "LY",
        "IR",
        "IQ",
        "SA",
        "MU",
        "SY",
        "AE",
        "LB",
        "DJ",
        "SO",
        "SS",
        "YT",
        "YE",
        "RE",
        "OM",
        "DZ",
        "QA",
        "CA",
        "TD",
        "PS",
      ],
      alertType: "auto",
      shortStatus: "RCB won",
      matchImageId: 626297,
    },
    venueInfo: {
      established: 1864,
      capacity: "63000",
      knownAs: null,
      ends: "High Court End, Pavilion End",
      city: "Kolkata",
      country: "India",
      timezone: "+05:30",
      homeTeam: "Bengal, Kolkata Knight Riders",
      floodlights: true,
      curator: "Probir Mukherjee",
      profile:
        "<b>Venue Description</b>:\n\nOne of the biggest sporting centres, Kolkata's Eden Garden holds a special place of interest in the history of Indian cricket. Capable of holding more than one lakh people at one stage, the capacity has now been reduced to a little more than 66,000 after the stadium underwent renovation before the 2011 World Cup.\n\nReferred as \"Cricket's answer to the Colosseum,\" the Eden Gardens, the largest cricket stadium in India, has hosted many prominent matches. The Eden Gardens crowd simply loves their sport. The first World Cup final outside Lord's was at this majestic venue. Anil Kumble's 6/12 against West Indies in the final of the 1993 Hero Cup was on this hallowed turf.  \n\nSachin Tendulkar's famous run-out during the Asian Test Championship match against Pakistan, resulted in Kolkata's mob fury in action once again - the match was eventually finished in front of empty stands. This wasn't the first time though - not to forget the previous instance, when India slumped to 120/8, chasing 252 against Sri Lanka in the semi-final of the 1996 World Cup. \n\nThere have been happier times as well. The 376-run stand between VVS Laxman and Rahul Dravid during the famous 2001 Test series against Australia, which inspired a famous Indian victory, came here. Rohit Sharma's belligerent ODI world record, a 173-ball 264, against Sri Lanka, in Nov 2014, also came on this famous ground.\n\nThe stadium hosted its first Test in 1934, with India hosting England. While the Test match came early, it had to wait until 1987 to host its first ODI, against Pakistan. While the stadium is synonymous with cricket, until 1984, it was also used as a football venue, with several of prominent derbies being held over the maidan. \n\n<b>How does the pitch play?</b>\n \nThe Eden Gardens track is considered as one of the better batting surfaces although spinners tend to come into action as the match wears on. Spinners have enjoyed bowling here in IPL games as well.\n\n<b>Stats and Trivia</b>\n\nThe highest ODI score by any batsman was made on this ground. Rohit Sharma smashed 264 against Sri Lanka in November, 2014\n\nEden Gardens has hosted as many as 39 Tests - the most by any venue in India.\n\nby <b>Pradeep Krishnamurthy</b>",
      imageUrl:
        "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/31.jpg",
      ground: "Eden Gardens",
      groundLength: 0,
      groundWidth: 0,
      otherSports: null,
    },
    broadcastInfo: [
      {
        country: "IN",
        broadcaster: [
          {
            broadcastType: "Streaming",
            value: "JioHotstar",
          },
          {
            broadcastType: "TV",
            value: "Star Sports Network",
          },
        ],
      },
    ],
  };

  const [data, setData] = useState([]);

  async function fetchMatchDetails() {
    const url = `https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/${id}`;
    const options = {
      method: "GET",
      headers: {
        "x-rapidapi-key": import.meta.env.VITE_API_KEY ,
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
      },
    };

    try {
      const response = await fetch(url, options);
      const result = await response.json();
      setData(result);
      console.log(result);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    // fetchMatchDetails()
  }, []);

  return (
    <>
      <div className="flex justify-center mt-2 mb-2 text-2xl hover:text-gray-500">MatchDetails</div>
      {/* {data.length <=0 ? <h1>loading..</h1> : */}
      <InpageNavigation
        teams={[
          fixedData.matchInfo.team1.shortName,
          fixedData.matchInfo.team2.shortName,
        ]}
      >
        {fixedData.matchInfo.team1.playerDetails.map((data,i) => (
          <div key={i} className="text-xl m-5 w-[50%]">
            <h1>{data.fullName}</h1>
            <h3 className="opacity-50 text-[17px]">{data.role}</h3>
          </div>
        ))}
        {fixedData.matchInfo.team2.playerDetails.map((data,i) => (
          <div key={i} className="text-xl relative left-60 lg:left-100 m-5 ">
          <h1>{data.fullName}</h1>
          <h3 className="opacity-50 text-[17px] ">{data.role}</h3>
        </div>
        ))}
      </InpageNavigation>
    </>
  );
};

export default MatchDetails;
